### ISSUE TITLE
Dropdownmarker at search Engine is missing

### ISSUE THREAD

**Issue by Endor8** [Baton34/organize-search-engines#87]
Hi.
The Dropdownmarker icon is missing at the search Engine.
Normally there is a Dropdownmarker at the right of the 
SearchEngine icon, to open the list or with OSE the Folders window.
Please fix this.
Thanks.
Endor

**Comment by Baton34** [comment]
Because Mozilla cut off more and more code with each new release.

**Comment by Endor8** [comment]
Thank you for the fast fix.
Works fine now.
Will you sign your Add-on, you know it is required for Firefox Finale and beta Versions.
Cheers
Endor

**Comment by Baton34** [comment]
I am not developer, I just little debug it for new FF version. I moved to ESR branch of FF because I tired of FF cutting off old useful feature.

**Comment by Endor8** [comment]
Yesterday I got a E-Mail from Malte Kraus, the original Author of Organize Search Engines.
I write in the same Forum as he, that's why we know each other.
He wrote me, that he is happy that someone has continued the work on this add-on.
He had no more time for developing or maintaining the OSE add-on. 
If you are interested, he likes to get in contact with you. This is also important for
clarifying the rights situation about this add-on. You can find his email address on this site:
https://maltekraus.de/blog/allgemein/2007/03/26/impressum.html
In case you like to sign your Version on AMO, which is really important, it is also better to
contact him. Maybe he could help you.
Cheers
Endor

**Comment by RAWRR** [comment]
You say you are no developer, just a debugger, but hey listen - how much activity happens now with this plugin at addons.mozilla.org under a "real" developer? That is right, none. And how much development do you think will happen with this plugin by some "real" developer over at addons.mozilla.org in the future? That also is pretty certainly zero.

Whatever you're doing is 100% better than the ~absolutely nothing~ that would be happening otherwise. Surprise! You're a real developer.

Please set it up over at mozilla!!
