### ISSUE TITLE
Multiple Search through Folders error

### ISSUE THREAD

**Issue by buthub** [Baton34/organize-search-engines#89]
To get the "Open All in Tabs" function (for any folder) to work, I have to select it twice in the search box.  It never seems to "take" in the first try, but does on the second.  I'm on FF 46.0.1.  Thanks.

**Comment by PlaceboPRS** [comment]
Firstly huge thanks for continuing this project it's my most missed addon of all time when it stopped working! My primary use was to be able to use one keyword to search multiple websites in new tabs for each, for example I'd have a "shopping" folder with a number of different online retailers and they'd all search for the same item.

Unfortunately I can't get this working at all, it used to be you middle click the folder and it opens all of the searches in new tabs, but nothing happens when I try that (nor when I try clicking "Open all in tabs".

Using 1.95.2 and I've tried latest Waterfox (my primary browser), latest firefox, even gone back to Firefox 46 but it doesn't work with any of them?

**Comment by Baton34** [comment]
**PlaceboPRS**
click on "Open All in Tabs" and then press Enter.
It is not fix, but works fo now.

**Comment by PlaceboPRS** [comment]
Hi, 

Firstly much thanks for replying.
When I click Open all in tabs and press enter nothing whatsoever happens :(

**Comment by Baton34** [comment]
I try it in FF 52.0a1 (2016-11-12) (32-bit) and in 49.0.2 with 1.95.2-fx version of OSE and it works.
Choose folder, type text in search bar, press Enter.

**Comment by PlaceboPRS** [comment]
I know this isn't the appropriate place but not sure where to post it!

Just want to say huge thanks this latest version is now working in Waterfox with all my other addons, I honestly thought I'd never see this crucial (IMO) extension working again after so many years with the original not working. Is there any way to donate a small something to you as way of thanks? :)

**Comment by Baton34** [comment]
Thanks for thanks : )
No need to donate, my contribution in ose too small. Thank the original author Malte Kraus.
